on: 
  push:
    branches:
      - master
  schedule:
    - cron: "*/15 * * * *"

name: Check services
jobs:
  build-bundle-deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install ping
        run: sudo apt-get install iputils-ping

      - name: Run checks
        env:
          STATUSPAGE_API_KEY: ${{ secrets.STATUSPAGE_API_KEY }}
          STATUSPAGE_PAGE_ID: ${{ secrets.STATUSPAGE_PAGE_ID }}
        run: python3 -m checker
